package drool
 
import monitor.MonitorMeasurement;
import monitor.MonitorController;
import controller.cloud.CloudManager;
 
rule "private cloud monitoring - processor"
    when
        m : MonitorMeasurement( m.getProcessor < 10 )
    then
    	m.isDanger();
        System.out.println( "private cloud monitoring detected problem - cores" );
end

rule "private cloud monitoring - load"
    when
        m : MonitorMeasurement( m.getLoad > 10 )
    then
    	m.isDanger();
        System.out.println( "private cloud monitoring detected problem - load" );
end

rule "private cloud monitoring - memory"
    when
        m : MonitorMeasurement( m.getMemory < 50)
    then
    	m.isDanger();
        System.out.println( "private cloud monitoring detected problem - memory" );
end

rule "private cloud monitoring - requests"
    when
        m : MonitorMeasurement( m.getNbRequests > 25)
    then
    	m.isDanger();
        System.out.println( "private cloud monitoring detected problem - requests" );
end

